### ISSUE TITLE
Migrating database taking forever

### ISSUE THREAD

**Issue by cracento** [WeebDev/chibisafe#267]
Just saw the updates to chibisafe, trying to migrate from v3 to v4 and I can't seem to migrate the database properly. I run the command, and it gets to 

`(node:3997254) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`.

It seems to hang at this point. I left it here for around 5 or 6 hours, and the photos did not migrate into the new website dashboard. They are also inaccessible, and just show up as a single pixel. Is there something I'm doing wrong? I followed the migration guide exactly.

**Comment by cracento** [comment]
[Here](https://ihatemateo.xyz/mln90l2qvl11.png) is a full log (this is the second time I've run this command).

yes I know I'm signing in as root and it's bad

**Comment by Pitu** [comment]
The error is `SQLITE_DONSTRAINT: UNIQUE constraint failed: files.id` which means something is being duplicated when it shouldn't. Did you run the migration twice perhaps?
It's having an issue copying the relation of the files over to the new database

**Comment by cracento** [comment]
This was the second time I had run the command. However, the first time I ran it, while I did not get that line if errors, it still hung at the same place.

**Comment by Pitu** [comment]
Well I can certainly say that the error you are getting now is due to trying to migrate twice. Unfortunately I don't know the first error you got so you'll need to start again. In order to do so, make sure to delete the newly created database and then run the migration again, it should be the `database/database.sqlite` file.
If it hangs again, please let me know and paste the entire output in something like hastebin. 
Thank you!

**Comment by cracento** [comment]
I don’t know exactly what the issue was, but I fixed it by deleting the sqlite file, rerunning `npm run setup` and then rerunning the migration command. Thanks for your help!
