### ISSUE TITLE
[BUG] Docker image not building

### ISSUE THREAD

**Issue by LeagueRaINi** [WeebDev/chibisafe#274]
**Describe the bug**
Currently the docker image is not building as node-gyp complains about not finding the `python` environment variable

**To Reproduce**
1. Follow the steps in the docker guide

**Expected behavior**
I expected it to successfully build

**Additional context**
The problem is probably related to python2 being deprecated now, the dockerfile pulling in specifically `node:alpine3.12` and doing an `apt update`
I got it to compile by upping the node version that is getting imported to `node:10.19.0-alpine`, not sure if thats the most elegant solution moving on tho

unrelated to this but the docker setup docs should probably be updated to make it clear that `./chibisafe` is supposed to be the shell file, experienced unix users might not have problems with this but i've seen ppl try executing the folder `chibisafe` which is in the same directory

**Comment by wildbook** [comment]
The issue seems to be caused by something specific to Node 16. Explicitly asking for an older version of Node solves the problem, but isn't exactly a proper fix.

That being said, if you don't care about running on older Node, explicitly asking for Node 15 by changing `FROM node:alpine3.12` to `FROM node:15-alpine3.12` should let you build it without issues.

**Comment by Pitu** [comment]
A bit late but the latest commit cb76049e02b87af7d4d8a4b7e71c4e01bc1d2a26 should solve the issue

**Comment by Pitu** [comment]
If you still encounter this problem feel free to re-open the issue
